/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConsentedFinancialAccount } from './consented-financial-account';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentedFinancialAccountFieldTransactionPeriod } from './consented-financial-account-field-transaction-period';
// May contain unused imports in some cases
// @ts-ignore
import { FinancialAccountDetailsRequired } from './financial-account-details-required';

/**
 * ConsentedFinancialAccountField : Consented financial account field details.
 * @export
 * @interface ConsentedFinancialAccountField
 */
export interface ConsentedFinancialAccountField {
    /**
     * Financial account field title.
     * @type {string}
     * @memberof ConsentedFinancialAccountField
     */
    'fieldTitle': string;
    /**
     * Financial account field slug.
     * @type {string}
     * @memberof ConsentedFinancialAccountField
     */
    'fieldSlug': string;
    /**
     * Requested financial account details.
     * @type {Array<FinancialAccountDetailsRequired>}
     * @memberof ConsentedFinancialAccountField
     */
    'requestedDetails': Array<FinancialAccountDetailsRequired>;
    /**
     * 
     * @type {ConsentedFinancialAccountFieldTransactionPeriod}
     * @memberof ConsentedFinancialAccountField
     */
    'transactionPeriod'?: ConsentedFinancialAccountFieldTransactionPeriod;
    /**
     * Consented financial accounts.
     * @type {Array<ConsentedFinancialAccount>}
     * @memberof ConsentedFinancialAccountField
     */
    'consentedAccounts': Array<ConsentedFinancialAccount>;
}

