/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DataConsentStatus } from './data-consent-status';

/**
 * Consent : Consent details.
 * @export
 * @interface Consent
 */
export interface Consent {
    /**
     * Consent id.
     * @type {string}
     * @memberof Consent
     */
    'id': string;
    /**
     * Consent request id.
     * @type {string}
     * @memberof Consent
     */
    'requestId': string;
    /**
     * Consent request template id.
     * @type {string}
     * @memberof Consent
     */
    'templateId'?: string;
    /**
     * Consent title.
     * @type {string}
     * @memberof Consent
     */
    'title': string;
    /**
     * Consent description.
     * @type {string}
     * @memberof Consent
     */
    'description': string;
    /**
     * Consent purpose.
     * @type {string}
     * @memberof Consent
     */
    'purpose'?: string;
    /**
     * 
     * @type {DataConsentStatus}
     * @memberof Consent
     */
    'status': DataConsentStatus;
    /**
     * Transaction id.
     * @type {string}
     * @memberof Consent
     */
    'transactionId'?: string;
    /**
     * Consent requested datetime in UTC timezone.
     * @type {string}
     * @memberof Consent
     */
    'requestedAtUtc': string;
    /**
     * Consent approval datetime in UTC timezone.
     * @type {string}
     * @memberof Consent
     */
    'approvedAtUtc'?: string;
    /**
     * Data access expiration datetime in UTC timezone.
     * @type {string}
     * @memberof Consent
     */
    'dataAccessExpiresAtUtc'?: string;
    /**
     * Consent revocation datetime in UTC timezone.
     * @type {string}
     * @memberof Consent
     */
    'revokedAtUtc'?: string;
}

