/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { CollectibleTypes } from './collectible-types';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentedDocument } from './consented-document';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentedFinancialAccount } from './consented-financial-account';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentedIdentifier } from './consented-identifier';
// May contain unused imports in some cases
// @ts-ignore
import { ConsentedMedicalRecord } from './consented-medical-record';
// May contain unused imports in some cases
// @ts-ignore
import { DataConsentStatus } from './data-consent-status';

/**
 * ConsentDetails : Consent details.
 * @export
 * @interface ConsentDetails
 */
export interface ConsentDetails {
    /**
     * Consent id.
     * @type {string}
     * @memberof ConsentDetails
     */
    'id': string;
    /**
     * Consent request id.
     * @type {string}
     * @memberof ConsentDetails
     */
    'requestId': string;
    /**
     * Consent request template id.
     * @type {string}
     * @memberof ConsentDetails
     */
    'templateId'?: string;
    /**
     * Consent title.
     * @type {string}
     * @memberof ConsentDetails
     */
    'title': string;
    /**
     * Consent description.
     * @type {string}
     * @memberof ConsentDetails
     */
    'description': string;
    /**
     * Consent purpose.
     * @type {string}
     * @memberof ConsentDetails
     */
    'purpose'?: string;
    /**
     * 
     * @type {DataConsentStatus}
     * @memberof ConsentDetails
     */
    'status': DataConsentStatus;
    /**
     * Transaction id.
     * @type {string}
     * @memberof ConsentDetails
     */
    'transactionId'?: string;
    /**
     * Consent approval datetime in UTC timezone.
     * @type {string}
     * @memberof ConsentDetails
     */
    'approvedAtUtc': string;
    /**
     * Data access expiration datetime in UTC timezone.
     * @type {string}
     * @memberof ConsentDetails
     */
    'dataAccessExpiresAtUtc': string;
    /**
     * Consent revocation datetime in UTC timezone.
     * @type {string}
     * @memberof ConsentDetails
     */
    'revokedAtUtc'?: string;
    /**
     * List of supported collectible types.
     * @type {Array<CollectibleTypes>}
     * @memberof ConsentDetails
     */
    'collectables': Array<CollectibleTypes>;
    /**
     * Consented identity details.
     * @type {Array<ConsentedIdentifier>}
     * @memberof ConsentDetails
     */
    'identifiers'?: Array<ConsentedIdentifier>;
    /**
     * List of consented documents.
     * @type {Array<ConsentedDocument>}
     * @memberof ConsentDetails
     */
    'documents'?: Array<ConsentedDocument>;
    /**
     * List of consented medical records.
     * @type {Array<ConsentedMedicalRecord>}
     * @memberof ConsentDetails
     */
    'medicalRecords'?: Array<ConsentedMedicalRecord>;
    /**
     * List of consented financial accounts.
     * @type {Array<ConsentedFinancialAccount>}
     * @memberof ConsentDetails
     */
    'financialAccounts'?: Array<ConsentedFinancialAccount>;
}

