/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DataConsentDocumentIssuer } from './data-consent-document-issuer';
import { DocumentDigitalSignature } from './document-digital-signature';

/**
 * Data Consent document details.
 * @export
 * @interface DataConsentDocument
 */
export interface DataConsentDocument {
    /**
     * Document id.
     * @type {string}
     * @memberof DataConsentDocument
     */
    id: string;
    /**
     * Document name.
     * @type {string}
     * @memberof DataConsentDocument
     */
    name: string;
    /**
     * Document category.
     * @type {string}
     * @memberof DataConsentDocument
     */
    category: string;
    /**
     * Document identifier.
     * @type {string}
     * @memberof DataConsentDocument
     */
    identifier: string;
    /**
     * Document field title.
     * @type {string}
     * @memberof DataConsentDocument
     */
    fieldTitle: string;
    /**
     * Document field slug.
     * @type {string}
     * @memberof DataConsentDocument
     */
    fieldSlug: string;
    /**
     * Document issued at datetime in UTC timezone.
     * @type {string}
     * @memberof DataConsentDocument
     */
    issuedAtUtc: string;
    /**
     * Document expires at datetime in UTC timezone.
     * @type {string}
     * @memberof DataConsentDocument
     */
    expiresAtUtc?: string | null;
    /**
     * 
     * @type {DataConsentDocumentIssuer}
     * @memberof DataConsentDocument
     */
    issuer: DataConsentDocumentIssuer;
    /**
     * Digital signatures.
     * @type {Array<DocumentDigitalSignature>}
     * @memberof DataConsentDocument
     */
    digitalSignatures: Array<DocumentDigitalSignature>;
}


