/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * OpenAPI spec version: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { DataConsentRequestedDocumentDto } from './DataConsentRequestedDocumentDto';
import { DataConsentRequestedFaDto } from './DataConsentRequestedFaDto';
import { DataFetchFrequencyUnit } from './DataFetchFrequencyUnit';
import { DataFetchType } from './DataFetchType';
import { DataLifeUnit } from './DataLifeUnit';
import { IdentityClaim } from './IdentityClaim';
import { HttpFile } from '../http/http';

export class DataConsentRequestModel {
    'organizationId'?: string;
    'transactionId'?: string;
    'identifiers'?: { [key: string]: string; };
    'startDateTime'?: Date;
    'expiryDateTime'?: Date;
    'description'?: string;
    'purposeCode'?: string;
    'purposeLink'?: string;
    'dataLifeUnit'?: DataLifeUnit;
    'dataLifeValue'?: number;
    'dataFetchFrequencyUnit'?: DataFetchFrequencyUnit;
    'dataFetchFrequencyUnitValue'?: number;
    'dataFetchType'?: DataFetchType;
    'agreementId'?: string;
    'identityClaims'?: Array<IdentityClaim>;
    'financialAccounts'?: Array<DataConsentRequestedFaDto>;
    'documents'?: Array<DataConsentRequestedDocumentDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "organizationId",
            "baseName": "organizationId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "transactionId",
            "baseName": "transactionId",
            "type": "string",
            "format": ""
        },
        {
            "name": "identifiers",
            "baseName": "identifiers",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "startDateTime",
            "baseName": "startDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "expiryDateTime",
            "baseName": "expiryDateTime",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "purposeCode",
            "baseName": "purposeCode",
            "type": "string",
            "format": ""
        },
        {
            "name": "purposeLink",
            "baseName": "purposeLink",
            "type": "string",
            "format": ""
        },
        {
            "name": "dataLifeUnit",
            "baseName": "dataLifeUnit",
            "type": "DataLifeUnit",
            "format": ""
        },
        {
            "name": "dataLifeValue",
            "baseName": "dataLifeValue",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dataFetchFrequencyUnit",
            "baseName": "dataFetchFrequencyUnit",
            "type": "DataFetchFrequencyUnit",
            "format": ""
        },
        {
            "name": "dataFetchFrequencyUnitValue",
            "baseName": "dataFetchFrequencyUnitValue",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "dataFetchType",
            "baseName": "dataFetchType",
            "type": "DataFetchType",
            "format": ""
        },
        {
            "name": "agreementId",
            "baseName": "agreementId",
            "type": "string",
            "format": "uuid"
        },
        {
            "name": "identityClaims",
            "baseName": "identityClaims",
            "type": "Array<IdentityClaim>",
            "format": ""
        },
        {
            "name": "financialAccounts",
            "baseName": "financialAccounts",
            "type": "Array<DataConsentRequestedFaDto>",
            "format": ""
        },
        {
            "name": "documents",
            "baseName": "documents",
            "type": "Array<DataConsentRequestedDocumentDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return DataConsentRequestModel.attributeTypeMap;
    }
    
    public constructor() {
    }
}

