/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentReceiver } from './document-receiver';
import { PaymentRequest } from './payment-request';

/**
 * Document Issue Request.
 * @export
 * @interface DocumentIssueRequest
 */
export interface DocumentIssueRequest {
    /**
     * Document type id.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    documentTypeId: string;
    /**
     * Document identifier.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    identifier: string;
    /**
     * Document description.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    description: string;
    /**
     * 
     * @type {DocumentReceiver}
     * @memberof DocumentIssueRequest
     */
    receiver: DocumentReceiver;
    /**
     * Datetime of issue in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    issuedAtUtc: string;
    /**
     * Valid from datetime in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    validFromUtc: string;
    /**
     * Datetime of expiry in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequest
     */
    expiresAtUtc?: string | null;
    /**
     * 
     * @type {PaymentRequest}
     * @memberof DocumentIssueRequest
     */
    paymentRequest?: PaymentRequest;
    /**
     * Metadata.
     * @type {{ [key: string]: string; }}
     * @memberof DocumentIssueRequest
     */
    metadata?: { [key: string]: string; } | null;
}


