/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentIssueRequestStatus } from './document-issue-request-status';

/**
 * Document issue request details.
 * @export
 * @interface DocumentIssueRequestDetails
 */
export interface DocumentIssueRequestDetails {
    /**
     * Document issue request Id.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    id: string;
    /**
     * Document type Id.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    documentTypeId: string;
    /**
     * Document type name.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    typeName: string;
    /**
     * Document identifier.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    identifier: string;
    /**
     * 
     * @type {DocumentIssueRequestStatus}
     * @memberof DocumentIssueRequestDetails
     */
    status: DocumentIssueRequestStatus;
    /**
     * Document description.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    description: string;
    /**
     * Document receiver details.
     * @type {any}
     * @memberof DocumentIssueRequestDetails
     */
    receiver: any | null;
    /**
     * Datetime of issue in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    issuedAtUtc: string;
    /**
     * Valid from datetime in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    validFromUtc: string;
    /**
     * Datetime of expiry in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    expiresAtUtc?: string | null;
    /**
     * Metadata.
     * @type {any}
     * @memberof DocumentIssueRequestDetails
     */
    metaData?: any | null;
    /**
     * Creation datetime of issue request in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    createdAtUtc: string;
}


