/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentCategoryType } from './document-category-type';
import { DocumentSubCategoryType } from './document-sub-category-type';
import { SupportedEntityType } from './supported-entity-type';

/**
 * Issuable Document Type details.
 * @export
 * @interface DocumentType
 */
export interface DocumentType {
    /**
     * Document Type Identifier.
     * @type {string}
     * @memberof DocumentType
     */
    id: string;
    /**
     * 
     * @type {DocumentCategoryType}
     * @memberof DocumentType
     */
    categoryType: DocumentCategoryType;
    /**
     * 
     * @type {DocumentSubCategoryType}
     * @memberof DocumentType
     */
    subCategoryType: DocumentSubCategoryType;
    /**
     * Document Type Name. eg: Driving License.
     * @type {string}
     * @memberof DocumentType
     */
    name: string;
    /**
     * Document Type Unique Slug. eg: \"in.gov.gj.transport.dl\".
     * @type {string}
     * @memberof DocumentType
     */
    slug: string;
    /**
     * Document Type description. eg: Gujarat State Driving License.
     * @type {string}
     * @memberof DocumentType
     */
    description?: string | null;
    /**
     * Logo URL of document type.
     * @type {string}
     * @memberof DocumentType
     */
    logoUrl: string;
    /**
     * Document search repository service name.
     * @type {string}
     * @memberof DocumentType
     */
    searchServiceName?: string | null;
    /**
     * Document repository service name.
     * @type {string}
     * @memberof DocumentType
     */
    repositoryServiceName?: string | null;
    /**
     * Supported entity types. eg: Individual, Organization.
     * @type {Array<SupportedEntityType>}
     * @memberof DocumentType
     */
    supportedEntityTypes: Array<SupportedEntityType>;
    /**
     * Name of the document type creator.
     * @type {string}
     * @memberof DocumentType
     */
    addedBy: string;
    /**
     * Payable amount if document is chargeable. eg: 10.25.
     * @type {number}
     * @memberof DocumentType
     */
    payableAmount?: number | null;
    /**
     * Payable amount currency. eg: INR, USD etc.,.
     * @type {string}
     * @memberof DocumentType
     */
    payableAmountCurrency?: string | null;
    /**
     * DateTime of approval in UTC timezone.
     * @type {string}
     * @memberof DocumentType
     */
    approvedAtUtc?: string | null;
    /**
     * Document type approval status.
     * @type {boolean}
     * @memberof DocumentType
     */
    approved: boolean;
}


