/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { DocumentIssueRequestDetailsReceiver } from './document-issue-request-details-receiver';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentIssueRequestStatus } from './document-issue-request-status';
// May contain unused imports in some cases
// @ts-ignore
import { PaymentRequest } from './payment-request';

/**
 * DocumentIssueRequestDetails : Document issue request details.
 * @export
 * @interface DocumentIssueRequestDetails
 */
export interface DocumentIssueRequestDetails {
    /**
     * Document issue request Id.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'id': string;
    /**
     * Document type Id.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'documentTypeId': string;
    /**
     * Document type name.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'typeName': string;
    /**
     * Document identifier.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'identifier': string;
    /**
     * 
     * @type {DocumentIssueRequestStatus}
     * @memberof DocumentIssueRequestDetails
     */
    'status': DocumentIssueRequestStatus;
    /**
     * Document description.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'description': string;
    /**
     * 
     * @type {DocumentIssueRequestDetailsReceiver}
     * @memberof DocumentIssueRequestDetails
     */
    'receiver': DocumentIssueRequestDetailsReceiver;
    /**
     * 
     * @type {PaymentRequest}
     * @memberof DocumentIssueRequestDetails
     */
    'paymentRequest'?: PaymentRequest;
    /**
     * Datetime of issue in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'issuedAtUtc': string;
    /**
     * Valid from datetime in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'validFromUtc': string;
    /**
     * Datetime of expiry in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'expiresAtUtc'?: string;
    /**
     * Metadata.
     * @type {any}
     * @memberof DocumentIssueRequestDetails
     */
    'metaData'?: any;
    /**
     * Creation datetime of issue request in UTC timezone.
     * @type {string}
     * @memberof DocumentIssueRequestDetails
     */
    'createdAtUtc': string;
}

