/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * IdentityField : Identity field of Consent request template.
 * @export
 * @interface IdentityField
 */
export interface IdentityField {
    /**
     * Field title.
     * @type {string}
     * @memberof IdentityField
     */
    'title': string;
    /**
     * Field description.
     * @type {string}
     * @memberof IdentityField
     */
    'description'?: string;
    /**
     * Field key.
     * @type {string}
     * @memberof IdentityField
     */
    'key': string;
    /**
     * Field data type.
     * @type {string}
     * @memberof IdentityField
     */
    'dataType': string;
}

