/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { ConsentRequestTemplateStatus } from './consent-request-template-status';
// May contain unused imports in some cases
// @ts-ignore
import { DocumentField } from './document-field';
// May contain unused imports in some cases
// @ts-ignore
import { FinancialAccountField } from './financial-account-field';
// May contain unused imports in some cases
// @ts-ignore
import { IdentityField } from './identity-field';
// May contain unused imports in some cases
// @ts-ignore
import { IndividualConsentRequestTemplateDetailsDataFrequency } from './individual-consent-request-template-details-data-frequency';
// May contain unused imports in some cases
// @ts-ignore
import { IndividualConsentRequestTemplateDetailsDataLife } from './individual-consent-request-template-details-data-life';
// May contain unused imports in some cases
// @ts-ignore
import { IndividualConsentRequestTemplateDetailsRequestLife } from './individual-consent-request-template-details-request-life';
// May contain unused imports in some cases
// @ts-ignore
import { MedicalRecordField } from './medical-record-field';

/**
 * IndividualConsentRequestTemplateDetails :  Individual consent request template details.
 * @export
 * @interface IndividualConsentRequestTemplateDetails
 */
export interface IndividualConsentRequestTemplateDetails {
    /**
     * Consent request template id.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'id': string;
    /**
     * Consent request template title.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'title': string;
    /**
     * Consent request template description.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'description': string;
    /**
     * Consent request template purpose.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'purpose'?: string;
    /**
     * Consent request template short Id.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'shortId': string;
    /**
     * 
     * @type {ConsentRequestTemplateStatus}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'status': ConsentRequestTemplateStatus;
    /**
     * 
     * @type {IndividualConsentRequestTemplateDetailsDataLife}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'dataLife'?: IndividualConsentRequestTemplateDetailsDataLife;
    /**
     * 
     * @type {IndividualConsentRequestTemplateDetailsRequestLife}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'requestLife'?: IndividualConsentRequestTemplateDetailsRequestLife;
    /**
     * 
     * @type {IndividualConsentRequestTemplateDetailsDataFrequency}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'dataFrequency'?: IndividualConsentRequestTemplateDetailsDataFrequency;
    /**
     * Consent request template identity fields.
     * @type {Array<IdentityField>}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'identifiers'?: Array<IdentityField>;
    /**
     * Consent request template document fields.
     * @type {Array<DocumentField>}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'documents'?: Array<DocumentField>;
    /**
     * Consent request template medical record fields.
     * @type {Array<MedicalRecordField>}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'medicalRecords'?: Array<MedicalRecordField>;
    /**
     * Consent request template financial account fields.
     * @type {Array<FinancialAccountField>}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'financialAccounts'?: Array<FinancialAccountField>;
    /**
     * Consent request template created by user.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'createdBy': string;
    /**
     * Consent request template created datetime in UTC timezone.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'createdAtUtc': string;
    /**
     * Consent request template approval datetime in UTC timezone.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'approvedAtUtc'?: string;
    /**
     * Consent request template published datetime in UTC timezone.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'publishedAtUtc'?: string;
    /**
     * Consent request template rejection datetime in UTC timezone.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'rejectedAtUtc'?: string;
    /**
     * Consent request template rejection reason.
     * @type {string}
     * @memberof IndividualConsentRequestTemplateDetails
     */
    'rejectionReason'?: string;
}

