/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentDigitalSignature } from './document-digital-signature';
import { DocumentReceiver } from './document-receiver';

/**
 * 
 * @export
 * @interface IssuedDocumentDetails
 */
export interface IssuedDocumentDetails {
    /**
     * Document Id.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    id: string;
    /**
     * Document Identifier.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    identifier: string;
    /**
     * Document type name.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    documentType: string;
    /**
     * User name.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    issuedTo: string;
    /**
     * Issued datetime in UTC timezone.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    issuedAtUtc: string;
    /**
     * Expires datetime in UTC timezone.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    expiresAtUtc?: string | null;
    /**
     * Accepted datetime in UTC timezone.
     * @type {string}
     * @memberof IssuedDocumentDetails
     */
    acceptedAtUtc?: string | null;
    /**
     * 
     * @type {DocumentReceiver}
     * @memberof IssuedDocumentDetails
     */
    receiver: DocumentReceiver;
    /**
     * Metadata.
     * @type {{ [key: string]: string; }}
     * @memberof IssuedDocumentDetails
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * Digital signatures.
     * @type {Array<DocumentDigitalSignature>}
     * @memberof IssuedDocumentDetails
     */
    digitalSignatures: Array<DocumentDigitalSignature>;
}


