/* tslint:disable */
/* eslint-disable */
/**
 * My Data My Consent - Developer API
 * Unleashing the power of data consent by establishing trust. The Platform Core Developer API defines a set of capabilities that can be used to request, issue, manage and update data, documents and credentials by organizations. The API can be used to request, manage and update Decentralised Identifiers, Financial Data, Health Data issue Documents, Credentials directly or using OpenID Connect flows, and verify Messages signed with DIDs and much more.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@mydatamyconsent.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OrganizationDocumentDetails
 */
export interface OrganizationDocumentDetails {
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    organizationId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    organizationName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    typeId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    typeName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    identifier?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    storageUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    countryIso2?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    issuerId?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationDocumentDetails
     */
    issuerName?: string | null;
}


